# Markdown renderer configuration
[goldmark.renderer]
  unsafe = true

[goldmark.parser]
  wrapStandAloneImageWithinParagraph = false
  [goldmark.parser.attribute]
    block = true
    title = true

[highlight]
  style = "base16-snazzy"

[tableOfContents]
  endLevel   = 4
  ordered    = true
  startLevel = 1
