[[main]]
  name = "透過 RSS 訂閱"
  url = "/zh/index.xml"
  weight = 10
  identifier = "rss-zh"
  [main.params]
    icon = "rss"
    newTab = true

[[social]]
  identifier = "github"
  name       = "GitHub"
  url        = "https://github.com/AngeCI"
  [social.params]
    icon = "brand-github"

[[social]]
  identifier = "more"
  name       = "More products"
  url        = "https://angeci.github.io"
  [social.params]
    icon = "dots"
