# Pages placed under these sections will be shown on homepage and archive page.
mainSections = [""]
# Output page's full content in RSS.
rssFullContent = true

[footer]
    since      = 2026

[dateFormat]
    published   = ":date_full"
    lastUpdated = ":date_full"

[article]
    headingAnchor = true
    readingTime   = true

[widgets]
    homepage = [
        { type = "search" },
        { type = "archives" },
        { type = "categories" },
        { type = "tag-cloud" },
    ]
    page = [{ type = "toc" }]

[colorScheme]
    toggle  = true
    default = "auto"
